baseURL = "https://dang-nh-cen.github.io/dangcode-blog/"
languageCode = "vi"
title = "Blog DangnoHat"
theme = "ananke"
buildDrafts = true
[pagination]
  pagerSize = 5
[params]
  author = "ÄÄƒng Nguyá»…n Háº£i"
  description = "Blog chia sáº» kiáº¿n thá»©c láº­p trÃ¬nh máº¡ng, Java vÃ  JavaScript."
  featured_image = "images/cover.jpg"
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


relativeURLs = false
canonifyURLs = true


[menu]
 [[menu.main]]
  name = "ğŸ  Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "ğŸ“ Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "ğŸš€ HÆ°á»›ng dáº«n"
  url = "/huong_dan_java/"
  weight = 3
  identifier = "cta-java"

[[menu.main]]
  name = "ğŸ’¬ Cáº£m nháº­n"
  url = "/cam_nhan/"
  weight = 4



  [[menu.main]]
    name = "ğŸ’« Giá»›i thiá»‡u cÃ¡ nhÃ¢n"
    url = "/profile/"
    weight = 5



